[package]
name = "models"
version = "0.1.0"
authors = ["Fabio Moreno <fabio.moreno@cuemby.com>"]
edition = "2018"

[dependencies]
protobuf        = "2"
futures         = "0.*"
futures-cpupool = "0.1.*"
tls-api         = "0.1.*"
grpc = "0.6.1"