// This file is generated by rust-protobuf 2.5.0. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

#[derive(PartialEq,Clone,Default)]
pub struct AddRequest {
    // message fields
    pub number1: f64,
    pub number2: f64,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a AddRequest {
    fn default() -> &'a AddRequest {
        <AddRequest as ::protobuf::Message>::default_instance()
    }
}

impl AddRequest {
    pub fn new() -> AddRequest {
        ::std::default::Default::default()
    }

    // double number1 = 1;


    pub fn get_number1(&self) -> f64 {
        self.number1
    }
    pub fn clear_number1(&mut self) {
        self.number1 = 0.;
    }

    // Param is passed by value, moved
    pub fn set_number1(&mut self, v: f64) {
        self.number1 = v;
    }

    // double number2 = 2;


    pub fn get_number2(&self) -> f64 {
        self.number2
    }
    pub fn clear_number2(&mut self) {
        self.number2 = 0.;
    }

    // Param is passed by value, moved
    pub fn set_number2(&mut self, v: f64) {
        self.number2 = v;
    }
}

impl ::protobuf::Message for AddRequest {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.number1 = tmp;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.number2 = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.number1 != 0. {
            my_size += 9;
        }
        if self.number2 != 0. {
            my_size += 9;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.number1 != 0. {
            os.write_double(1, self.number1)?;
        }
        if self.number2 != 0. {
            os.write_double(2, self.number2)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> AddRequest {
        AddRequest::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "number1",
                    |m: &AddRequest| { &m.number1 },
                    |m: &mut AddRequest| { &mut m.number1 },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "number2",
                    |m: &AddRequest| { &m.number2 },
                    |m: &mut AddRequest| { &mut m.number2 },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<AddRequest>(
                    "AddRequest",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static AddRequest {
        static mut instance: ::protobuf::lazy::Lazy<AddRequest> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const AddRequest,
        };
        unsafe {
            instance.get(AddRequest::new)
        }
    }
}

impl ::protobuf::Clear for AddRequest {
    fn clear(&mut self) {
        self.number1 = 0.;
        self.number2 = 0.;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for AddRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for AddRequest {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct AddResponse {
    // message fields
    pub result: f64,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a AddResponse {
    fn default() -> &'a AddResponse {
        <AddResponse as ::protobuf::Message>::default_instance()
    }
}

impl AddResponse {
    pub fn new() -> AddResponse {
        ::std::default::Default::default()
    }

    // double result = 1;


    pub fn get_result(&self) -> f64 {
        self.result
    }
    pub fn clear_result(&mut self) {
        self.result = 0.;
    }

    // Param is passed by value, moved
    pub fn set_result(&mut self, v: f64) {
        self.result = v;
    }
}

impl ::protobuf::Message for AddResponse {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.result = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.result != 0. {
            my_size += 9;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.result != 0. {
            os.write_double(1, self.result)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> AddResponse {
        AddResponse::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "result",
                    |m: &AddResponse| { &m.result },
                    |m: &mut AddResponse| { &mut m.result },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<AddResponse>(
                    "AddResponse",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static AddResponse {
        static mut instance: ::protobuf::lazy::Lazy<AddResponse> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const AddResponse,
        };
        unsafe {
            instance.get(AddResponse::new)
        }
    }
}

impl ::protobuf::Clear for AddResponse {
    fn clear(&mut self) {
        self.result = 0.;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for AddResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for AddResponse {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x13proto/example.proto\x12\x06netsaj\"@\n\nAddRequest\x12\x18\n\x07nu\
    mber1\x18\x01\x20\x01(\x01R\x07number1\x12\x18\n\x07number2\x18\x02\x20\
    \x01(\x01R\x07number2\"%\n\x0bAddResponse\x12\x16\n\x06result\x18\x01\
    \x20\x01(\x01R\x06result2@\n\x0eExampleService\x12.\n\x03Add\x12\x12.net\
    saj.AddRequest\x1a\x13.netsaj.AddResponseJ\xed\x02\n\x06\x12\x04\0\0\x0f\
    \x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\n\x01\x02\x12\x03\x02\0\x0f\n\
    \n\n\x02\x04\0\x12\x04\x04\0\x07\x01\n\n\n\x03\x04\0\x01\x12\x03\x04\x08\
    \x12\n\x0b\n\x04\x04\0\x02\0\x12\x03\x05\x04\x17\n\r\n\x05\x04\0\x02\0\
    \x04\x12\x04\x05\x04\x04\x13\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\x05\x04\
    \n\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x05\x0b\x12\n\x0c\n\x05\x04\0\x02\
    \0\x03\x12\x03\x05\x15\x16\n\x0b\n\x04\x04\0\x02\x01\x12\x03\x06\x04\x17\
    \n\r\n\x05\x04\0\x02\x01\x04\x12\x04\x06\x04\x05\x17\n\x0c\n\x05\x04\0\
    \x02\x01\x05\x12\x03\x06\x04\n\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\x06\
    \x0b\x12\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\x06\x15\x16\n\n\n\x02\x04\
    \x01\x12\x04\t\0\x0b\x01\n\n\n\x03\x04\x01\x01\x12\x03\t\x08\x13\n\x0b\n\
    \x04\x04\x01\x02\0\x12\x03\n\x04\x16\n\r\n\x05\x04\x01\x02\0\x04\x12\x04\
    \n\x04\t\x14\n\x0c\n\x05\x04\x01\x02\0\x05\x12\x03\n\x04\n\n\x0c\n\x05\
    \x04\x01\x02\0\x01\x12\x03\n\x0b\x11\n\x0c\n\x05\x04\x01\x02\0\x03\x12\
    \x03\n\x14\x15\n\n\n\x02\x06\0\x12\x04\r\0\x0f\x01\n\n\n\x03\x06\0\x01\
    \x12\x03\r\x08\x16\n\x0b\n\x04\x06\0\x02\0\x12\x03\x0e\x04/\n\x0c\n\x05\
    \x06\0\x02\0\x01\x12\x03\x0e\x08\x0b\n\x0c\n\x05\x06\0\x02\0\x02\x12\x03\
    \x0e\r\x17\n\x0c\n\x05\x06\0\x02\0\x03\x12\x03\x0e\"-b\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
